# Generated by Django 4.2.10 on 2024-02-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='user_id',
            new_name='user',
        ),
    ]
